project:
  type: website

website:
  title: "assign"
  reader-mode: true
  repo-url: https://github.com/coatless-quarto/assign/
  repo-actions: [edit, issue]
  sidebar:
    style: "floating"
    search: true
    tools:
      - icon: github
        href: https://github.com/coatless-quarto/assign/
    contents: 
      - text: "Home"
        file: index.qmd
      - section: "Demo"
        contents:
        - text: Assign Document
          href: https://quarto.thecoatlessprofessor.com/assign/demo/assign
        - text: Solution Document
          href: https://quarto.thecoatlessprofessor.com/assign/demo/solution
        - text: Rubric Document
          href: https://quarto.thecoatlessprofessor.com/assign/demo/rubric
      - section: "Support"
        contents:
        - text: "Submit an issue"
          href: https://github.com/coatless-quarto/assign/issues/new/choose
      - section: "Extra"
        contents:
        - qassign-release-notes.qmd

format: 
  html:
    toc: true